package br.ce.wcaquino.servicos;

import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import br.ce.wcaquino.exceptions.SemDivisaoPorZero;



public class CalculadoraTest {
@Test
public void somar() {
	

//cenario
int a = 5;
int b = 8;
Calculadora calc = new Calculadora ();
//ação
int resultado = calc.somar(a, b);

//verificação
 Assert.assertEquals(13,resultado);
}

@Test
public void subtracao() {
	
	//cenario
	int a = 9;
	int b = 7;
	Calculadora calc = new Calculadora();
	
	//ação;
	int resultado = calc.subtrair(a,b);
	
	//verificação
	Assert.assertEquals(2, resultado);
}

@Test
public void multiplicacao() {
	//cenario
	int a = 9;
	int b = 7;
	Calculadora calc = new Calculadora();
	
	//ação;
	int resultado = calc.multiplicar(a,b);
	
	//verificação
	Assert.assertEquals(63, resultado);
}

@Test
public void divisao() throws SemDivisaoPorZero {
	//cenario
	int a = 100;
	int b = 10;
	Calculadora calc = new Calculadora();
	
	//ação;
	int resultado = calc.dividir(a,b);
	
	//verificação
	Assert.assertEquals(10, resultado);
}


@Test (expected = SemDivisaoPorZero.class)
public void divisaoSemDividirPorZero() throws SemDivisaoPorZero {
	//cenario
	int a = 10;
	int b = 2;
	Calculadora calc = new Calculadora();
	
	//ação;
	calc.dividir(a,b);
	

}



}
